- orbis-kernel/src/utils/Logs.cpp
Fixes the following errors:
`orbis-kernel/src/utils/Logs.cpp:8:42: error: 'std::uintmax_t' has not been declared`
`orbis-kernel/src/utils/Logs.cpp:17:41: error: 'uintptr_t' in namespace 'std' does not name a type`
> Fix build failure with gcc-13

- CMakeLists.txt
- orbis-kernel/CMakeLists.txt
- rpcsx-gpu/CMakeLists.txt
- rpcsx-os/CMakeLists.txt
- Enforce CXX Standard
- use Find_package to find `Vulkan` and `glfw3`
- targets include their `cmake_current_source_dir`  in place of `.`
> Find packages and sane include dirs

- orbis-kernel/CMakeLists.txt
Fix undefined references (since https://github.com/RPCSX/rpcsx/commit/450fd30889b43a55cfb9355948ef56b272ba7144) when linking with `-Wl,-z,defs` in `LDFLAGS`.
`orbis-kernel-shared` does not seem to be used anywhere by the way.
> orbis-kernel: fix linking

- hw/amdgpu/lib/libspirv/include/spirv/spirv-builder.hpp
Fix an issue with the pushRegion function, which modifies/duplicates (in a way that leads to undefined behavior) the id definitions and uses of its own fields instead of adding the ones from the other region.
> [amdgpu] libspirv: Fix pushRegion

- orbis-kernel/include/orbis/AudioOut.hpp
- orbis-kernel/src/sys/sys_sce.cpp
- orbis-kernel/src/sys/sys_vm_mmap.cpp
- rpcsx-os/CMakeLists.txt
- rpcsx-os/io-device.cpp
- rpcsx-os/main.cpp
Need the sox library for sound playback
`apt install sox` for ubuntu
`pacman -S sox` for Arch
The `-a` or `--enable-audio` flag must be set to enable sound in the game.
This implementation works only if the application uses one audio port, it has not been tested with two, but it is likely to crash.
> Basic audio output implementation

- rpcsx-os/iodev/shm.cpp
This allows the emulator to work on samples and Sonic Mania on a firmware version higher than 5.05.
Not sure if this is the right thing to do in long term, but thought might share a quick fix.
> Add SceAvSetting for higher firmware versions

- orbis-kernel/CMakeLists.txt
- rpcsx-os/CMakeLists.txt
`sox` is used in `orbis::kernel` not in `rpcsx-os`. Fix undefined references when linking with `-Wl,-z,defs` in `LDFLAGS`.
> cmake: fix sox linking

- orbis-kernel/include/orbis/AudioOut.hpp
- orbis-kernel/src/sys/sys_sce.cpp
This PR presents a more proper parsing of Control Shared Memory
- It uses a specific offset (which does not seem to change from firmware to firmware) that can be used to accurately retrieve the structure of a specific port unlike the previous implementation by searching for the first non-empty byte.
- Used mutex to wait for device initialization via sox, without it application crashed due to simultaneous initialization
- Added the last two unknown 8-channel S16 and F32 formats with postfix `_STD`, testing showed that they sound the same as normal S16 and F32 formats.
Since the sample of applications was not large, the test was performed on two games with one output and on a custom homebrew sample with three outputs, no problems were noticed and in addition `--trace` no longer crashes the …
> AudioOut: relatively correct parsing

- rx/CMakeLists.txt
Fix git detection when `cmake` is not executed from within the source directory, i.e. `cmake -S path/to/src -B path/to/build`.
> [rx] cmake: fix git detection

- rpcsx-os/iodev/dce.cpp
For cases when eop_nz=1 flip the task is placed in the eop waiting queue, instead of the flip queue itself from the gnm subsystem and responds with a special token to the address in eop_val which is used to identify the flip
Maximum flip queue size = 32
Maximum waiting queue eop size = 18
> Fix of data structures for dev dce

- .github/BUILDING.md
This removes the second way for arch to install spriv-cross as its easier / better to just use YAY.  
This also fixes the warning to make it an actual warning and stand out a bit more.
> Remove 2nd instructions for arch. Make warning stand out

- .editorconfig
'spaces' is not a valid value for indent_style
ref: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_style
> [editorconfig] 'spaces' >> 'space'

- .github/workflows/rpcsx.yml
- rpcsx-os/CMakeLists.txt
Make the target architecture a user preference, only hardcode the required flags.
> cmake: un-hardcode native architecture

- CMakeLists.txt
- rpcsx-gpu/CMakeLists.txt
- rpcsx-os/CMakeLists.txt
`-Ttext-segment` is only supported by `bfd`/`gold`.
The ([possibly](https://github.com/rui314/mold/issues/871)?) equivalent `--image-base` is supported by `bfd`, `lld` and `mold`.
> cmake: fix link with lld and mold

- orbis-kernel/include/orbis/AudioOut.hpp
- rpcsx-os/main.cpp
If the `-a` or `--enable-audio` flag is specified, use ipmi emulation without audio daemon
New changes:
- Improved synchronization, now sound should arrive on time and stutter less (but tested only in three games)
Not supported with `--system` flag
> Emulate audio system without audio daemon

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/rpcsx.yml
- .github/workflows/tidy-comments.yml
Updates actions to newer versions, which should resolve deprecation warnings.
`clang-tidy` and `clang-format` have also been updated to 18.
> infra: update workflows

- .github/BUILDING.md
- .github/workflows/rpcsx.yml
- rpcsx-os/CMakeLists.txt
- rpcsx-os/audio/AlsaDevice.cpp
- rpcsx-os/audio/AlsaDevice.hpp
- rpcsx-os/audio/AudioDevice.cpp
- rpcsx-os/audio/AudioDevice.hpp
- rpcsx-os/io-devices.hpp
- rpcsx-os/iodev/aout.cpp
- rpcsx-os/main.cpp
This PR triggers the creation of devices from the audio daemon and adds audio playback from those devices:
- Unlike the daemon emulation, this implementation allows the sound to be heard in vsh, but this cannot be tested at the moment as vsh still does not reach the music playback stage on startup
- It's a very rough implementation, so the sound can be very rough compared to the demon emulation
- Also, alsa-lib is used here instead of sox, since the future plan is to replace sox with a universal playback interface with multiple backends  and also use it in daemon emulation (or remove daemon emulation)
- At the moment this only works from firmwares >=5.05
- In case of startup problems, you can also run daemon emulation via `-a` flag, this will skip starting the audio daemon
> Audio daemon playback support

- rpcsx-os/CMakeLists.txt
Use the internal [FindALSA](https://cmake.org/cmake/help/latest/module/FindALSA.html) module.
> cmake: use ALSA imported target

- orbis-kernel/include/orbis/umtx.hpp
- orbis-kernel/src/sys/sys_umtx.cpp
Cleanup, doesn't implement any new behaviour.
According to FreeBSD docs, case 23 should be `UMTX_OP_SEM2_WAIT`, but I'm not sure if the same applies to Orbis, so I've left it unimplemented.
> orbis-kernel: Define umtx ops in header

- 3rdparty/CMakeLists.txt
- rpcsx/CMakeLists.txt
- rpcsx/iodev/ajm.cpp
- rpcsx/iodev/ajm.hpp
This PR is marked as draft as it is still in development and is not recommended to be pushed into the main branch
**What works**:
- Simple At9 decoding
- Simple MP3 decoding
- Simple ADTS AAC decoding
- Simple Audiodec
**What doesn't work**:
- ring buffer jobs
- it's not async, so it blocks the thread while decoding
- doesn't work properly
**What needs to be done**:
Mostly untested in games
Once this works well in synchronous, it will need to make an asynchronous task queue, since on the original platform, AJM works with a separate hardware and it works without blocking the main hardware threads (at least until you ask for it)
> AJM decode PoC

- rpcsx/ipmi.cpp
This fixes the name of the SceNpScoreIpc event flag, fixing issues with libSceNpScore's module init failing.
This progresses SWORD ART ONLINE: FATAL BULLET (CUSA10093) slightly further, though the game still crashes before it can show anything.
[Sword Art Online Fatal Bullet logs pre-fix.zip](https://github.com/user-attachments/files/22198603/Sword.Art.Online.Fatal.Bullet.logs.pre-fix.zip)
[Sword Art Online Fatal Bullet logs post-fix.zip](https://github.com/user-attachments/files/22198602/Sword.Art.Online.Fatal.Bullet.logs.post-fix.zip)
This also brings Sword Art Online: Lost Song further, though it seems to be stuck on a loading screen.
> ipmi: fix hex formatting for SceNpScoreIpc event flag name

- rpcsx/ops.cpp
Most errors that can be thrown by `vm::virtualQuery` result in an ACCES error code on real hardware, rather than the FAULT error code currently used here.
Fixing this error return fixes the current hang in Grand Theft Auto V (CUSA00419), now the game plays a little bit of audio then hangs on something else.
Logs:
[Before.zip](https://github.com/user-attachments/files/22348189/Before.zip)
[After.zip](https://github.com/user-attachments/files/22348188/After.zip)
> vm: Fix virtual_query error code
